### ISSUE TITLE
Error on boot: socket: -115

### ISSUE THREAD

**Issue by ghost** [Louisvh/NDS-controller#7]
Hi,

When I start up the app on my old 3ds (Luma3ds and installed via the .cia file in FBI) I get a black screen with in red: "socket: -115". Beneath it it says in white text: "Press B to exit". When I press B, it says: "Waiting for SocExit...". 
After redownloading and reinstalling the .cia file it gives the same error.
I also loaded the .3dsx file from the homebrew launcher, but that still gave an error.
Any thoughts?

Wessel

**Comment by jistjak** [comment]
BUMP
I also got the same error. I'm gonna check the code to find what this means. If i can understand it. Hopefully i can

**Comment by jistjak** [comment]
One thing i found was a hard coded 192.168.001.001 ip address.  My gateway (and many other people's gateway) is 10.0.0.1. Maybe the socket error might have something to do with the invalid 192 ip? I'm just guessing. If i had the tools to build the project i would test my theory.

**Comment by Louisvh** [comment]
That is not the problem. The "hard coded" ip address is just the initial default value: it is not used before the user is prompted to change it. The socket error means the socket initialization in 3DS-controller.c:195 does not complete successfully. -115 means the socket took too long to set up and control is passed back to the program. The code assumes something is terribly wrong if socket creation failed (as I never ran into the problem myself) but in this case, that is a bit overeager.

You might be able to fix it by busy-waiting on the socket creation: just loop over the socket(...) call until the result is anything other than -115. I can't test it as I don't have the problem, but if that fixes it for you, I'll add it as a workaround.

Compiling shouldn't be too hard actually. Some info on what you need can be found [here](https://wiki.gbatemp.net/wiki/3DS_Homebrew_Development).

**Comment by ghost** [comment]
Well, I'll try that. (My coding skills suck)
I'll be on vacation soon, so I don't know if I can finish it...

Thanks,
Wessel

**Comment by Louisvh** [comment]
Just replace "if" in line 197 by "while", replace "failExit" in line 198 by "printf" and copy/paste the "sock = ..." statement from 195 to the inside of that while loop. Either that fixes it, or it will get stuck in a loop of trying but being unable to create the socket.

**Comment by ghost** [comment]
Did that, now trying to compile.

**Comment by ghost** [comment]
Ugh, prob. can't finish it. If someone wants to compile it, I pushed that little edit to https://github.com/GamingWessel/NDS-controller.

**Comment by jistjak** [comment]
Ok i was just guessing. I havent used any c type language in about 4 years.
And i saw that default gateway ipwas 192.bla bla and i recognized it as the
ip routers used but mine was 10.0.0.x. and so i thought that might be the
problem. I couldn't test my theory since i don't have a compiler and
haven't downloaded the huge program because i have 5mbps internet and
setting up the visual studio hasalways been a pain for me. Thank you for
responding though. I'll update my rating

**Comment by ghost** [comment]
I successfully installed the .cia via the QR-code after getting a new SD-card (SanDisk 32GB, first I had a generic crappy china card).
I have no clue if the sd card fixed it, or that my crummy wifi works, but here we are.
