### ISSUE TITLE
How do I change button mappings?

### ISSUE THREAD

**Issue by npease18** [Louisvh/NDS-controller#8]
I would like to customize this so that I can change the android side key outputs. I am running android 6.0 and the client is working. Is there a config file or something?

**Comment by Louisvh** [comment]
In the current version, that's not (easily) possible. You can look at the source for the Android-side of things [here](https://github.com/Louisvh/NDS-controller-android-host), and honestly, it's a bit of a mess. It was more of a quick hack to get things working well enough for me to control an emulator, and it went onto the big pile of "stuff I'll re-do properly once I have some time off" (which isn't going to happen any time soon, I'm afraid).

The easiest way to customize the key output is to grab the source from that link, change the keycodes in line 22 of [NDSControllerService.java](https://github.com/Louisvh/NDS-controller-android-host/blob/c038e19235a885c3e973ebd8b13a52d2b1eb4819/app/src/main/java/com/ldvhrtn/ndscontroller/NDSControllerService.java) and recompile it. If you've got an afternoon off to mess with it a bit and you build a basic configuration-something around it, I'll be glad to merge a pull request!

**Comment by npease18** [comment]
Ah okay. I will take a look!

**Comment by npease18** [comment]
~What do I need to build it? Gradle?~
~Nevermind, I think I got it. Now, where can I find a list of keycodes? Just google "Java Keycodes"?~
Found that as well, nevermind. It was the android keycodes itself... oops.

~Also, when I attempt to build both my copy and yours, the build is failing. I am using  the batch script~
All good!
